OPENAI_API_KEY="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"
OPENAI_MODEL_NAME="gpt-4o"
